### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by prateekiiest**

### CODE REVIEW

**Comment by prateekiiest** [comment]
I am sorry, if I am bothering you. I have sent a lot of PRs so far :)

**Comment by MrBlaise** [comment]
This shouldn't be in the main README. I've created a README inside the Sorting folder, this information should be inside that file :)

**Comment by prateekiiest** [comment]
This file was for installation procedures.

**Comment by MrBlaise** [comment]
Yes, but these are only needed when using the program you contributed inside the sorting folder (and even then not all of them needed eg.: panda) so this should'nt be in the main readme rather than a readme next to the actual file that needs it or in a comment inside that file

**Comment by prateekiiest** [comment]
Ok, got it.

**Pull request closed without merging**
